services:
  image-service-api:
    image: ${DOCKER_REGISTRY-}imageserviceapi
    build:
      context: .
      dockerfile: image-service-api/Dockerfile
    ports:
      - "5500:8080"
      - "5501:8081"
    environment:
      AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://image-service-storage:10000/devstoreaccount1;"
    depends_on:
      image-service-storage:
        condition: service_healthy
  image-service-storage:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: image-service-storage   
    ports:
      - "11000:10000"
      - "11001:10001"
      - "11002:10002"
    command: "azurite --loose --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0"
    environment:
      AZURITE_USE_DEFAULT_STORAGE_LOCATION: "true"
    volumes:
      - azurite_data:/data
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 10000 || exit 1"]
      interval: 1s
      retries: 30

volumes:
  azurite_data: